name: 2020 Practice Problem

on:
  push:
    paths:
    - './2020/prac/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run solver
      run: |
        cd ./2019/prac/
        python main.py -a
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: "2020-prac-output"
        # Directory containing files to upload
        path: "./2020/prac/output"
